owner: ServerDeveloper9447
repo: statuspage

sites:
  - name: Power Guilds Website
    url: https://powerguilds.foo.ng
  - name: Power Guilds Backend (If down but bot still running, it's likely on backup hosting)
    url: $NODE1
  - name: Power Guilds Web Dashboard
    url: https://dash.powerguilds.foo.ng
  - name: Power Guilds Web Dashboard (Backend)
    url: https://internal.powerguilds.foo.ng
  
status-website:
  cname: status.powerguilds.foo.ng
  theme: night
  # baseUrl: /
  logoUrl: https://powerguilds.foo.ng/assets/favicon.png
  favicon: https://powerguilds.foo.ng/assets/favicon.png
  name: Power Guilds Status Page
  introTitle: "Statuspage for tracking uptime of **Power Guilds** services."
  introMessage: All updates will be posted alongside on your [Guilded Server](https://guilded.gg/powerguilds).
  navbar:
    - title: Website
      href: https://powerguilds.foo.ng
    - title: Guilded
      href: https://guilded.gg/powerguilds
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
